<?php
ini_set('display_errors', 'On');
error_reporting(E_ALL | E_STRICT);
require_once 'db.php';
$fields = "timestamp, matchnum, team";
$values = "ADDTIME(NOW(), '1:00:00'), 38, 2567";
//Prefer to read the fields from a JSON or CSV file to make it easier to modify the list
//Any easy way to read the values in? Loop through an array input generated by jQuery?
$sql="INSERT INTO matches ($fields) VALUES ($values)";
if(mysqli_query($conn, $sql)){
echo "Submitted successfully";
} else{
echo "Error<br>".$sql."<br>".$conn->error;
//how to get the error in procedural style?
}
mysqli_close($conn);
?>